#!/bin/bash
set -u

# Exit on command errors and treat unset variables as an error

# Source app helpers
source /usr/share/yunohost/helpers

REMOVE_NGINX_CONF () {  # Suppression de la configuration nginx
        if [ -e "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then # Delete nginx config
                echo "Delete nginx config"
                sudo rm "/etc/nginx/conf.d/$domain.d/$app.conf"
        fi
}

REMOVE_FPM_CONF () {    # Suppression de la configuration du pool php-fpm
        if [ -e "/etc/php5/fpm/pool.d/$app.conf" ]; then        # Delete fpm config
                echo "Delete fpm config"
                sudo rm "/etc/php5/fpm/pool.d/$app.conf"
        fi
}

SECURE_REMOVE () {      # Suppression de dossier avec vérification des variables
        sudo rm -rf /varwww/$app
        sudo pear uninstall SeedDMS_Core
        sudo pear uninstall SeedDMS_Lucene
        sudo pear uninstall SeedDMS_Preview
}

REMOVE_BDD () { # Suppression de la base de donnée et de l'utilisateur associé.
# $1 = Nom de la base de donnée
        # Utilise '$app' comme nom d'utilisateur et de base de donnée
        db_user=$1
        if mysqlshow -u root -p$(sudo cat $MYSQL_ROOT_PWD_FILE) | grep -q "^| $db_user"; then
                echo "Delete db"
                ynh_mysql_drop_db $db_user
                ynh_mysql_drop_user $db_user
        fi
}

# Retrieve parameters
	app=$YNH_APP_INSTANCE_NAME
	domain=$(ynh_app_setting_get "$app" domain)

# Drop MySQL database and user
	REMOVE_BDD "$app"

# Delete app directory and configurations using secure remove
	SECURE_REMOVE
	REMOVE_NGINX_CONF
	REMOVE_FPM_CONF

# Reload services
	sudo service php5-fpm reload
	sudo service nginx reload